export const boxes = document.querySelectorAll(".box");//for each tictactoe box
export const curTurn = document.getElementById("status");//current turn
export const rBtn = document.getElementById("reset");//reset button
export const mBtn = document.getElementById("playerMode");//reset button
export const settingBtn = document.getElementById("settingBtn");
export const infiniteBtn = document.getElementById("infiniteBtn");
export const settingPanel = document.getElementById("settingPanel");
export const closeSetting = document.getElementById("closeSetting");
export const xPlayer = document.getElementById("xPlayer");
export const oPlayer = document.getElementById("oPlayer");
export const drawsLabel = document.getElementById("drawsLabel");
export const drawCountEl = document.getElementById("drawCount");
export const mBtn.textContent = "Single Player";
export const infiniteBtn.textContent = "Infinite Mode"; 